In [1]:
%matplotlib inline

In [2]:
import numpy as np
import matplotlib.pyplot as plt
from scipy.io import readsav

In [3]:
%load_ext autoreload
%autoreload 2
from DSTPolarimeterLib import *

---

In [27]:
MuellerMatrixMirror(0.1, 0.1)

array([[ 0.90909091,  0.09090909,  0.        ,  0.        ],
       [ 0.09090909,  0.90909091,  0.        ,  0.        ],
       [ 0.        ,  0.        , -0.90001513, -0.09030272],
       [ 0.        ,  0.        ,  0.09030272, -0.90001513]])

In [5]:
MuellerMatrixWaveplate(0.1,0.1)

array([[  1.00000000e+00,   0.00000000e+00,   0.00000000e+00,
          0.00000000e+00],
       [  0.00000000e+00,   9.99802817e-01,   9.72734838e-04,
         -1.98338381e-02],
       [  0.00000000e+00,   9.72734838e-04,   9.95201348e-01,
          9.78433950e-02],
       [  0.00000000e+00,   1.98338381e-02,  -9.78433950e-02,
          9.95004165e-01]])

In [6]:
MuellerMatrixRotation(1.0)

array([[ 1.        ,  0.        ,  0.        ,  0.        ],
       [ 0.        , -0.41614684,  0.90929743,  0.        ],
       [ 0.        , -0.90929743, -0.41614684,  0.        ],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])

In [10]:
parameterMMSP2Mirror(860)

(array([ 0.45982679, -0.01282763, -0.00128099,  0.00879521, -0.01589159,
         0.45353538, -0.04532575,  0.00105785,  0.00207759, -0.04286378,
        -0.39057072,  0.23015655,  0.00174064, -0.00873887, -0.23290975,
        -0.39321918]), 1462)

In [12]:
path = "/nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000.sav"
saveFile = readsav(path)

In [13]:
par=parameterDST(saveFile['hds'][0],th_mmsp2_hsp=(88.2 - 131.2)*dtor)       
par["xn"].set(value=-0.0387)
par["tn"].set(value=-16.8*dtor)
par["xc"].set(value=-0.0321)
par["tc"].set(value=12.5*dtor)
par["sc"].set(value=0.0521)
par

Parameters([('xn', <Parameter 'xn', -0.0387, bounds=[-1.0:1.0]>),
            ('tn', <Parameter 'tn', -0.29321544000000005, bounds=[-inf:inf]>),
            ('xc', <Parameter 'xc', -0.0321, bounds=[-1.0:1.0]>),
            ('tc', <Parameter 'tc', 0.21816625, bounds=[-inf:inf]>),
            ('sc', <Parameter 'sc', 0.0521, bounds=[0.0:1.0]>),
            ('t_en', <Parameter 't_en', value=0.0 (fixed), bounds=[-inf:inf]>),
            ('dlen', <Parameter 'dlen', value=0.0 (fixed), bounds=[-inf:inf]>),
            ('t_ex', <Parameter 't_ex', value=0.0 (fixed), bounds=[-inf:inf]>),
            ('dlex', <Parameter 'dlex', value=0.0 (fixed), bounds=[-inf:inf]>),
            ('th_dst_mmsp2',
             <Parameter 'th_dst_mmsp2', 0.0, bounds=[-3.141592653589793:3.141592653589793]>),
            ('th_mmsp2_hsp',
             <Parameter 'th_mmsp2_hsp', -0.7504918999999998, bounds=[-3.141592653589793:3.141592653589793]>),
            ('par_mmsp2_0',
             <Parameter 'par_mmsp2_0', value=0

In [22]:
zd, ha, r, p, i = hd2angle(saveFile['hds'])

In [26]:
i

array([ 5.20272008,  5.20319519,  5.2041454 ,  5.20459601,  5.20519735,
        5.20557073,  5.20655269,  5.20705411,  5.20823229,  5.21100517,
        5.21207204,  5.21280867,  5.21376368,  5.21442627,  5.21513574,
        5.21595066,  5.21679382,  5.21782564,  5.21888142,  5.22010999,
        5.22080348,  5.2217489 ,  5.2227087 ,  5.22368821,  5.2246869 ,
        5.22554689,  5.22646589,  5.22751304,  5.22908227,  5.23022308,
        5.23133362,  5.23246812,  5.23361701,  5.23537203,  5.2365646 ,
        5.23808207,  5.23962404,  5.24182967,  5.24311438,  5.2450734 ])

---

In [4]:
%run scipt_to_run_on_kipsua.py /nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000 /nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000

['scipt_to_run_on_kipsua.py', '/nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000', '/nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000']
pathData     :  /nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000
pathCamera01 :  /nwork/kouui/dstsp/data/calibration/20171128/camera01/cale_iquv0000
--- Preparing fitting process ---
ref_index ref_time ok.
calibration data dictionary ok.
Array iquv and hd ok.
iquv : 1.25 GB
order_no_bad ok.
mm45_flat, matImageRotatorSeries ok.
--- Start fitting process ---
> /tmp_mnt/home/kouui/cloud_computing/dstsp/calibration/DSTPolarimeterLib.py(212)residual()
-> return (y_model-data)/sigma
(Pdb) y_model
array([-0.31814982, -0.90580696,  0.33932698,  0.92681008, -0.35612137,
       -0.88604129,  0.36994938,  0.91385945,  0.01856935, -0.41361001,
       -0.8445284 ,  0.42505145,  0.88420147, -0.43778459, -0.82831429,
        0.44562787,  0.87247372,  0.02239727, -0.46333119, -0.80498197,
        0.47189314,  0.85

BdbQuit: 

---

# progress

1. `MuellerMatrixMirror` ok.
2. `MuellerMatrixWaveplate` ok.
3. `MuellerMatrixRotation` ok.
4. `parameterMMSP2Mirror` ok.
5. `parameterDST` ok.